package cmd

import (
	"fmt"
	"io"
	"regexp"
	"sort"
	"strings"

	"github.com/rclone/rclone/fs"
	"github.com/rclone/rclone/fs/config/flags"
	"github.com/rclone/rclone/fs/filter"
	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
	"golang.org/x/text/cases"
	"golang.org/x/text/language"
)

var GeneratingDocs = false

type helpState struct {
	backendFlags         map[string]struct{}
	filterFlagsGroup     string
	filterFlagsRe        *regexp.Regexp
	filterFlagsNamesOnly bool
}

func newHelpCommand(root *cobra.Command) *cobra.Command {
	return &cobra.Command{
		Use:   "help",
		Short: root.Short,
		Long:  root.Long,
		RunE: func(command *cobra.Command, args []string) error {
			root.SetOut(command.OutOrStdout())
			return root.Usage()
		},
	}
}

func newHelpFlagsCommand(root *cobra.Command, state *helpState) *cobra.Command {
	return &cobra.Command{
		Use:   "flags [<filter>]",
		Short: "Show the global flags for rclone",
		RunE: func(command *cobra.Command, args []string) error {
			command.Flags()

			if GeneratingDocs {
				root.SetUsageTemplate(docFlagsTemplate)
				return command.Usage()
			}

			state.filterFlagsRe = nil
			if len(args) > 0 {
				re, err := filter.GlobStringToRegexp(args[0], false, true)
				if err != nil {
					return fmt.Errorf("invalid flag filter: %w", err)
				}
				state.filterFlagsRe = re
				fs.Debugf(nil, "Flag filter: %s", re.String())
			}

			switch {
			case state.filterFlagsGroup != "":
				root.SetUsageTemplate(filterFlagsSingleGroupTemplate)
			case len(args) > 0:
				root.SetUsageTemplate(filterFlagsMultiGroupTemplate)
			default:
				root.SetUsageTemplate(usageTemplate)
			}

			root.SetOut(command.OutOrStdout())
			return command.Usage()
		},
	}
}

func newHelpBackendsCommand() *cobra.Command {
	return &cobra.Command{
		Use:   "backends",
		Short: "List the backends available",
		RunE: func(command *cobra.Command, args []string) error {
			return showBackends(command.OutOrStdout())
		},
	}
}

func newHelpBackendCommand() *cobra.Command {
	return &cobra.Command{
		Use:   "backend <name>",
		Short: "List full info about a backend",
		RunE: func(command *cobra.Command, args []string) error {
			if len(args) == 0 {
				return command.Usage()
			}
			return showBackend(command.OutOrStdout(), args[0])
		},
	}
}

func addBackendFlags(state *helpState, flagSet *pflag.FlagSet) {
	state.backendFlags = map[string]struct{}{}
	for _, fsInfo := range fs.Registry {
		flags.AddFlagsFromOptions(flagSet, fsInfo.Prefix, fsInfo.Options)
		for i := range fsInfo.Options {
			opt := &fsInfo.Options[i]
			state.backendFlags[opt.FlagName(fsInfo.Prefix)] = struct{}{}
		}
	}
}

var usageTemplate = `Usage:{{if .Runnable}}
  {{.UseLine}}{{end}}{{if .HasAvailableSubCommands}}
  {{.CommandPath}} [command]{{end}}{{if gt (len .Aliases) 0}}

Aliases:
  {{.NameAndAliases}}{{end}}{{if .HasExample}}

Examples:
{{.Example}}{{end}}{{if and (showCommands .) .HasAvailableSubCommands}}

Available commands:{{range .Commands}}{{if (or .IsAvailableCommand (eq .Name "help"))}}
  {{rpad .Name .NamePadding}} {{.Short}}{{end}}{{end}}{{end}}{{if and (showLocalFlags .) .HasAvailableLocalFlags}}

Flags:
{{.LocalFlags.FlagUsages | trimTrailingWhitespaces}}{{end}}{{if and (showGlobalFlags .) .HasAvailableInheritedFlags}}{{range flagGroups .}}{{if .Flags.HasFlags}}

{{.Help}} (flag group {{.Name}}):
{{.Flags.FlagUsages | trimTrailingWhitespaces}}{{end}}{{end}}{{end}}{{if .HasHelpSubCommands}}
 
Additional help topics:{{range .Commands}}{{if .IsAdditionalHelpTopicCommand}}
  {{rpad .CommandPath .CommandPathPadding}} {{.Short}}{{end}}{{end}}{{end}}

Use "rclone-cloud [command] --help" for more information about a command.
Use "rclone-cloud help flags" for to see the global flags.
Use "rclone-cloud help backends" for a list of supported services.
`

var filterFlagsSingleGroupTemplate = `{{range flagGroups .}}{{if .Flags.HasFlags}}{{.Flags.FlagUsages | trimTrailingWhitespaces}}
{{end}}{{end}}
`

var filterFlagsMultiGroupTemplate = `{{range flagGroups .}}{{if .Flags.HasFlags}}{{.Help}} (flag group {{.Name}}):
{{.Flags.FlagUsages | trimTrailingWhitespaces}}

{{end}}{{end}}`

var docFlagsTemplate = `---
title: "Global Flags"
description: "Rclone Global Flags"
# autogenerated - DO NOT EDIT
---

# Global Flags

This describes the global flags available to every rclone command
split into groups.

{{range flagGroups .}}{{if .Flags.HasFlags}}
## {{.Name}}

{{.Help}}.

` + "```" + `
{{.Flags.FlagUsages | trimTrailingWhitespaces}}
` + "```" + `

{{end}}{{end}}
`

func showBackends(out io.Writer) error {
	if _, err := fmt.Fprintln(out, "All rclone backends:"); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(out); err != nil {
		return err
	}

	for _, backend := range fs.Registry {
		if _, err := fmt.Fprintf(out, "  %-12s %s\n", backend.Prefix, backend.Description); err != nil {
			return err
		}
	}

	if _, err := fmt.Fprintln(out); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(out, "To see more info about a particular backend use:"); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(out, "  rclone help backend <name>"); err != nil {
		return err
	}
	return nil
}

func quoteString(v any) string {
	switch v.(type) {
	case string:
		return fmt.Sprintf("%q", v)
	default:
		return fmt.Sprint(v)
	}
}

func showBackend(out interface{ Write([]byte) (int, error) }, name string) error {
	backend, err := fs.Find(name)
	if err != nil {
		return err
	}

	var standardOptions, advancedOptions fs.Options
	done := map[string]struct{}{}

	for _, opt := range backend.Options {
		if _, exists := done[opt.Name]; exists {
			continue
		}
		done[opt.Name] = struct{}{}
		if opt.Advanced {
			advancedOptions = append(advancedOptions, opt)
		} else {
			standardOptions = append(standardOptions, opt)
		}
	}

	optionsType := "standard"
	for _, opts := range []fs.Options{standardOptions, advancedOptions} {
		if len(opts) == 0 {
			optionsType = "advanced"
			continue
		}

		title := cases.Title(language.Und, cases.NoLower).String(optionsType)
		_, _ = fmt.Fprintf(out, "### %s options\n\n", title)
		_, _ = fmt.Fprintf(out, "Here are the %s options specific to %s (%s).\n\n", optionsType, backend.Name, backend.Description)
		optionsType = "advanced"

		for _, opt := range opts {
			shortOpt := ""
			if opt.ShortOpt != "" {
				shortOpt = fmt.Sprintf(" / -%s", opt.ShortOpt)
			}
			_, _ = fmt.Fprintf(out, "#### --%s%s\n\n", opt.FlagName(backend.Prefix), shortOpt)
			_, _ = fmt.Fprintf(out, "%s\n\n", opt.Help)

			if opt.IsPassword {
				_, _ = fmt.Fprintf(out, "**NB** Input to this must be obscured - see [rclone obscure](/commands/rclone_obscure/).\n\n")
			}

			_, _ = fmt.Fprintf(out, "Properties:\n\n")
			_, _ = fmt.Fprintf(out, "- Config:      %s\n", opt.Name)
			_, _ = fmt.Fprintf(out, "- Env Var:     %s\n", opt.EnvVarName(backend.Prefix))
			if opt.Provider != "" {
				_, _ = fmt.Fprintf(out, "- Provider:    %s\n", opt.Provider)
			}
			_, _ = fmt.Fprintf(out, "- Type:        %s\n", opt.Type())

			defaultValue := opt.GetValue()
			if defaultValue != "" {
				_, _ = fmt.Fprintf(out, "- Default:     %s\n", quoteString(defaultValue))
			} else {
				_, _ = fmt.Fprintf(out, "- Required:    %v\n", opt.Required)
			}

			if len(opt.Examples) > 0 {
				if opt.Exclusive {
					_, _ = fmt.Fprintf(out, "- Choices:\n")
				} else {
					_, _ = fmt.Fprintf(out, "- Examples:\n")
				}
				for _, ex := range opt.Examples {
					_, _ = fmt.Fprintf(out, "  - %s\n", quoteString(ex.Value))
					for line := range strings.SplitSeq(ex.Help, "\n") {
						_, _ = fmt.Fprintf(out, "    - %s\n", line)
					}
					if ex.Provider != "" {
						_, _ = fmt.Fprintf(out, "    - Provider: %s\n", ex.Provider)
					}
				}
			}
			_, _ = fmt.Fprintf(out, "\n")
		}
	}

	if backend.MetadataInfo != nil {
		_, _ = fmt.Fprintf(out, "### Metadata\n\n")
		_, _ = fmt.Fprintf(out, "%s\n\n", strings.TrimSpace(backend.MetadataInfo.Help))

		if len(backend.MetadataInfo.System) > 0 {
			_, _ = fmt.Fprintf(out, "Here are the possible system metadata items for the %s backend.\n\n", backend.Name)

			keys := make([]string, 0, len(backend.MetadataInfo.System))
			for k := range backend.MetadataInfo.System {
				keys = append(keys, k)
			}
			sort.Strings(keys)

			_, _ = fmt.Fprintf(out, "| Name | Help | Type | Example | Read Only |\n")
			_, _ = fmt.Fprintf(out, "|------|------|------|---------|-----------|\n")
			for _, k := range keys {
				v := backend.MetadataInfo.System[k]
				ro := "N"
				if v.ReadOnly {
					ro = "**Y**"
				}
				_, _ = fmt.Fprintf(out, "| %s | %s | %s | %s | %s |\n", k, v.Help, v.Type, v.Example, ro)
			}
			_, _ = fmt.Fprintf(out, "\n")
		}

		_, _ = fmt.Fprintf(out, "See the [metadata](/docs/#metadata) docs for more info.\n\n")
	}

	return nil
}
