##################################################################
# A Github action used to build and push the Web API Docker image
##################################################################

name: Publish Web API
on:
  push:
    branches: [main]
    paths:
      - "apps/web-api/**"
      - ".github/workflows/publish-web-api.yaml"

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build, package, and publish the Web API to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7
        with:
          egress-policy: audit

      - name: "Checkout GitHub Action"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Login to Docker Hub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate timestamp tag for Docker image
        run: echo "TIMESTAMP_TAG=$(date +%Y%m%d_%H%M%S)" >> $GITHUB_ENV

      - name: Create Docker image metadata
        id: docker-metadata
        uses: docker/metadata-action@8e534005b82cb22b9195aeb21a8d5f303f848a3f
        with:
          images: ekarton/rclone-on-cloud-webapi
          tags: |
            type=raw,value=latest
            type=raw,value=${{ env.TIMESTAMP_TAG }}

      - name: Build and push to Docker Hub
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25
        with:
          push: true
          context: ./apps/web-api
          file: ./apps/web-api/Dockerfile
          tags: ${{ steps.docker-metadata.outputs.tags }}
          labels: ${{ steps.docker-metadata.outputs.labels }}
